### PR TITLE
Fix storybook

### PR DESCRIPTION
**Pull request by pradel**
When I run storybook I got a regenerator error. Move babel-polyfill at the top of storybook config fix the issue.

capture d ecran 2017-01-20 a 11 12 04

### CODE REVIEW

**Comment by pradel** [comment]
I still get some errors with storybook. Looks like `<AccountsClient.ui.LoginForm />` is undefined.
capture d ecran 2017-01-20 a 12 00 06

**Comment by TimMikeladze** [comment]
To fix that undefined login form error,  do `import './index` which will assign all the components to `AccountsClient.ui`

**Comment by pradel** [comment]
It is already imported here https://github.com/js-accounts/react/blob/master/packages/material-ui/src/Accounts.story.js#L6

**Comment by TimMikeladze** [comment]
Hmm I'm not sure then. I can do some digging into this or do you wanto?

**Comment by pradel** [comment]
If you can look into it I will be able to do the semantic-ui part next week

**Comment by TimMikeladze** [comment]
Will do!

**Comment by TimMikeladze** [comment]
This will be fixed as part of #26

**Pull request closed without merging**
